baseURL = "https://loweschmidt.se"
title = "Lowe Schmidt"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

# buildDrafts = false
# # include content with publishdate in the future
# buildFuture = false
# # include content already expired
# buildExpired = false
# # enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
# relativeURLs = true
# disableRSS = true
# enableRobotsTXT = true
# editor = "vim"

[markup.highlight]
style = "github-dark"

# [blackfriday]
# extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:year/:month/:slug/"

[params]
author = "Lowe Schmidt"
info = "SRE & DevOps, Hoppy IPAs, Tattoos and Homebrewing."
description = "I am a father of two, a site reliability engineer and a fan of modal text editors, hoppy beer and tattoos.\n\n I am not great at web development (duh...)"
avatarurl = "img/avatar2.jpg"
keywords = "sre,devops,homebrewing,linux,programming,golang"
#since = 2008
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Email"
icon = "fa-brands fa-email fa-2x"
email = "hello@loweschmidt.se"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
url = "https://github.com/lsc"

[[params.social]]
name = "GitLab"
icon = "fa-brands fa-gitlab fa-2x"
url = "https://gitlab.com/lsc"


[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
url = "https://instagram.com/loweschmidt"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
url = "https://www.linkedin.com/in/loweschmidt"

[[params.social]]
name = "Threads"
icon = "fa-brands fa-threads fa-2x"
url = "https://www.threads.com/@loweschmidt"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"


[[menu.main]]
name = "About"
weight = 2
url = "about/"
